Added the documentation and the skript for lightweight solution
abelsiqueira/asreview-cloud pull request #6
Opened 2023-06-07 21:23 UTC by zoneout215

2023-06-08 10:27 UTC, abelsiqueira requested changes
Thanks for the script and the update in the file.
I made some comments, but that was a great job.
Also, add the bash file directly to the root.

After we merge this, I will refactor the files and the documentation.
We can talk more in the afternoon.

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +## Lightweight usage
```suggestion
## Lightweight usage

```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +it is possible to test it utilizing functionality of [GNU Project package](https://www.gnu.org/software/parallel). For such type test follow these steps:
I like to format MD files by having one sentence per line. Like this:
```suggestion
If you want to use parallelization, but can't, or don't want to, use Kubernetes, it is possible to use [GNU Project package](https://www.gnu.org/software/parallel) to parallelize the execution of the script locally.
For such usage follow these steps:
```
It becomes easier to update later.
I also made some suggestions

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +1. Download and install the GNU package following the instructions. We recommend to install the package via package managers if you have one (such as `homebrew` or `chocolatte`), but in case you do n
I'm removing the numbering since it extends over many lines, so it is easier to maintain.
```suggestion
Install the package [GNU parallel](https://www.gnu.org/software/parallel/) following the instructions on the website.
We recommend installing the package via package managers if you have one (such as `apt-get`, `homebrew` or `chocolatey`).

> **Note**
>
> For SURF, that would be `sudo apt-get install parallel`.

In case you do not have one, you can follow the steps below:
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +Run those commands `parallel-*` will be a downloaded file with a number instead of '*':
```suggestion

**Linux and MacOS**

Make sure that you have `wget` installed.
Run these commands (`parallel-NUMBER` is the extracted file name):
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +sudo tar -xjf parallel-latest.tar.bz2
```suggestion
tar -xjf parallel-latest.tar.bz2
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +cd parallel-*
```suggestion
cd parallel-NUMBER
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +make install
```suggestion
sudo make install
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +* If you are using Windows, we suggest following this [guide](https://stackoverflow.com/questions/52393850/how-to-install-gnu-parallel-on-windows-10-using-git-bash#52451011).
```suggestion
**Windows**

We suggest following this [guide](https://stackoverflow.com/questions/52393850/how-to-install-gnu-parallel-on-windows-10-using-git-bash#52451011).
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +2. Run  in your command line to check if the package is installed.
```suggestion
Check that the package is installed with

```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +as was described above, not multiprocessing writing files to directories before creating those:
```suggestion
To parallelize your `jobs.sh` file, we need to split it into blocks that can be parallelized.
```
I didn't understand the "multiprocessing" part.

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +5. Then run this command, specifiing the argument of number of cores. We recommend not to use all of your CPU cores at ones (leave at least one or two) for the sake of your machine safety.
```suggestion
Then you can just run the script below, specifying the number of cores as an argument.
We recommend not using all of your CPU cores at once.
Leave at least one or two to allow your machine to process other tasks.
Notice that there is no limitation on memory usage per task, so for models that use a lot of memory, there might be some competition for resources.
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +sh parallel_run.sh <the_number_of_cores>
```suggestion
bash parallel_run.sh <the_number_of_cores>
```

2023-06-08 10:27 UTC, abelsiqueira commented on README.md
> +TODO: the run of bash script for Windows
If you can test this, it will be interesting. Probably just a mention of using jobs.bat instead, although I really don't know.

2023-06-08 10:27 UTC, abelsiqueira commented on #!/bin/parallel_run.sh
> +parallel -j "$num_cores" < jobs.sh.part1
```suggestion
bash jobs.sh.part1
```
Some of this first part actually needs to be run sequentially. I think it doesn't fail because it runs fast enough.
Then the asreview metrics can be parallelized. I am not sure, so probably best to run sequentially, and maybe we could split even more in the future, if we understand how this works.

2023-06-08 12:18 UTC, zoneout215 commented on README.md
> +as was described above, not multiprocessing writing files to directories before creating those:
I just wanted to add a brief explanation about why we need to split the file, but changes are fine for me

2023-06-16 07:49 UTC, abelsiqueira commented
Hi @zoneout215, thanks for the update, but I think you missed many of the comments I made. I noticed that you marked some of the comments as resolved, but there was no update on them.
I agree with dropping support for Windows.

2023-06-16 09:05 UTC, zoneout215 commented
> Hi @zoneout215, thanks for the update, but I think you missed many of the comments I made. I noticed that you marked some of the comments as resolved, but there was no update on them.
> I agree with dropping support for Windows.

Oh, my appologies, I thought that when you resolve them, the changes are accepted, will do in a moment

2023-06-16 09:30 UTC, zoneout215 reviewed
I have commited the changes with slight altering (just put the 'number of cores' instruction into a warining format)

2023-06-16 09:51 UTC, abelsiqueira commented on README.md
> +TODO: the run of bash script for Windows
```suggestion
```bash
bash parallel_run.sh <the_number_of_cores>
```
```

I removed some empty lines and I think we will remove this message because it's related to Windows support, right?

2023-06-16 09:52 UTC, abelsiqueira commented on README.md
> +We suggest following this [guide](https://stackoverflow.com/questions/52393850/how-to-install-gnu-parallel-on-windows-10-using-git-bash#52451011) or install [anaconda environment](https://docs.anacon
Do you want to remove this, since Windows is not supported anymore?

2023-06-16 13:05 UTC, zoneout215 commented on README.md
> +We suggest following this [guide](https://stackoverflow.com/questions/52393850/how-to-install-gnu-parallel-on-windows-10-using-git-bash#52451011) or install [anaconda environment](https://docs.anacon
I have removed it, thanks for pointing out

2023-06-16 13:06 UTC, zoneout215 reviewed
Have removed installation for Windows and the bash run commands for Windows

2023-06-16 14:05 UTC, abelsiqueira approved these changes
Thanks for the changes. Great addition.

2023-06-16 14:06 UTC, merged